import { DataTypes } from './dataType';
export interface Group {
    _id: string,
    name_ka: string,
    name_en: string,
    shortDescription: string,
   students?: [],
   mentors: [],
   courseId: string,
   endDate?: string,
   startDate: string,
   level: string,
   payze: string,
   price: string,
   locationName: string,
   locationLink: string,
   schedule: [string],
   times: [string],
   type: DataTypes.GROUP,
    photo?: string,
  mentor?: string,
  mentorPhoto?: string,
  id: string,
  days: string,
  time: string,
}